import { Info } from "lucide-react";

export function AiDisclaimer({ className = "" }: { className?: string }) {
  return (
    <div
      className={`flex items-start gap-2 rounded-lg border border-border bg-muted/50 px-3 py-2 text-xs text-muted-foreground ${className}`}
    >
      <Info className="mt-0.5 h-3.5 w-3.5 shrink-0" />
      <p>
        Responsible AI: outputs are generated by AI and may be inaccurate or incomplete. Review and
        edit before sending, sharing, or acting on anything. Avoid entering sensitive personal data.
      </p>
    </div>
  );
}
